version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  api:
    build: .
    container_name: express_container
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "${PORT}:5000"
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  postgres_data:
    driver: local